server:
  port: 8080
spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: 8cde85444a324a1eda6f
            clientSecret: 907eab6c58811c9a8aa425be7306f9959d469b55
            scope:
              - email
              - profile
              - email
              - address
              - phone

  datasource:
    url: jdbc:postgresql://localhost:5436/postgres
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  liquibase:
    change-log: changelog/db.changelog-master.yaml